### ISSUE TITLE
SEOmetrics gives error 500

### ISSUE THREAD

**Issue by superwick** [khalwat/seomatic#86]
When I attempt to view SEOmetrics on a live preview, nothing loads in the popup dialog. When I look at the console, there's an error 500 on the request to `{domain}/index.php/actions/seomatic/renderMetrics?url={pageUrl}` and looking at that particular response I see:

> Internal Server Error
> Call to undefined function DaveChild\TextStatistics\utf8_decode()

**Comment by khalwat** [comment]
Interesting.  Do you have the complete stack trace I could see?

**Comment by khalwat** [comment]
It looks like potentially your version of PHP doesn't have the XML parsers compiled into it?

http://osticket.com/forum/discussion/8702/php-fatal-error-call-to-undefined-function-utf8-encode-error-message

**Comment by superwick** [comment]
Yep, I think that was it.... I recently updated to php 7.0 and I did not install the xml php mods. Installed php7.0-xml and restarted apache and it seems to work just fine now. Thanks.

**Comment by khalwat** [comment]
I updated the README.md with this requirements info, in case anyone else runs into it:

https://github.com/nystudio107/seomatic/blob/master/README.md

**Comment by cavidano** [comment]
I use Liquidweb and am getting the same 500 error. Locally everything runs beautifully. I am new to Craft and I love this plug-in - not sure what steps to take? I tried installing the latest version from the repo and the error persists.

**Comment by khalwat** [comment]
@cavidano It's probably the same issue we've discussed here, which is that the PHP install is incomplete. This article might be useful to you:

https://nystudio107.com/blog/web-hosting-for-agencies-freelancers
